### ISSUE TITLE
Problem with check_working_folder()

### ISSUE THREAD

**Issue by Omniferum** [juancarlospaco/css-html-js-minify#20]
--INPUT (WITH FOLDER PATH)
c:\Python34\python.exe css-html-js-minify.py 1\test.css

--OUTPUT
Nothing. Just a blank line. However the file does get processed, whereas with previous commits I got pretty much: https://raw.githubusercontent.com/juancarlospaco/css-html-js-minify/master/windows-css-html-js-compressor.jpg

--INPUT (WITHOUT FOLDER PATH)
c:\Python34\python.exe css-html-js-minify.py test.css

--OUTPUT
Blank, except for the following:
CRITICAL:root:Folder  does not exist !.
Folder  does not exist !.

I recall you saying something about changing the output error message but I never did test what changes you made (if any). Not that it matters as i'm sure most people have this as part of a set of build tools that only reference full paths.

The concern I had with this vague error wording is when you get to debugging. It's easier to place your 'test.css' into the same folder as the python script so you can make changes to it and check output for consistency or to see what broke.

For windows machine though it would be as simple as just adding: os.path.dirname(sys.argv[0])

So if windows and that error is thrown, try os.path.dirname(sys.argv[0]) + path, and if still error then throw the final error.

**Comment by juancarlospaco** [comment]
Not annoying, is very useful, we are making great advance thanks to your contribution !  :smile_cat: 


We added a method to check the working folder, for enough space, permissions, etc,
problem is that it fails if its not a folder or is a path but cant extract a folder path from it, it fails,
that should be fixed now, it seems to work as previously

```python
juan@z:~/code/css-html-js-minify$ python3 css-html-js-minify.py temp/sorttest.css

Unix SysLog Server not found,ignored Logging to SysLog.                                                                                                    
Logger created with Log file at: /tmp/css-html-js-minify.log.                                                                                              
CSS-HTML-JS-Minify.                                                                                                                                        
                                                                                                                                                           
StandAlone Async single-file cross-platform no-dependencies                                                                                                
Unicode-ready Python3-ready Minifier for the Web.                                                                                                          
                                                                                                                                                           
Python 3.4.0 on Linux-3.13.0-52-generic-x86_64-with-Ubuntu-14.04-trusty. 
STDIN Encoding:  utf-8. 
STDERR Encoding:  utf-8. 
STDOUT Encoding: utf-8
Default Encoding: utf-8. 
FileSystem Encoding: ascii. 
PYTHONIOENCODING Encoding:  utf-8. 
Process Name set to: css-html-js-minify. 
Creating Abstract UDP Socket Lock for Single Instance. 
Socket Lock for Single Instance: <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketType.SOCK_STREAM, proto=0, laddr=b'\x00_your_app_name_here__lock'>.                                                                                                                                                    
Checking the Working Folder: 'temp' 
Total Free Space: ~52 GigaBytes.
Target is a CSS File.
Processing CSS file: temp/sorttest.css.
INPUT: Reading CSS file temp/sorttest.css.
Compressing CSS...
Removing all Comments.
Removing unnecessary Quotes on selectors of CSS classes.
Condensing all unnecessary white spaces.
Removing quotes from url.
Condensing extended named color values.
Condensing font weights on values.
Removing all unnecessary white spaces.
Condensing standard named color values.
Removing all unnecessary semicolons.
Condensing all zeroes on values.
Condensing all multidimensional zeroes on values.
Condensing all floating point values.
Converting all rgba to hexadecimal color values.
Condensing all hexadecimal color values.
Condense borders values.
Condensing all unnecessary multiple adjacent semicolons.
Adding encoding declaration if needed.
Finished compressing CSS !.
Prepending '.MIN.CSS' Prefix to temp/sorttest.css.
OUTPUT: Writing CSS Minified temp/sorttest.min.css.
--------------------------------------------------------------------------------
Files Processed: temp/sorttest.css.
Number of Files Processed: 1.
Total Maximum RAM Memory used: ~61 MegaBytes.
Total Working Time: 0:00:00.021245.

juan@z:~/code/css-html-js-minify$
```

**Comment by Omniferum** [comment]
Just got the latest commit and the problems seem to still exist. Tried it a few times before deciding to post as commenting in a 'closed' thing feels odd to me.

**Comment by juancarlospaco** [comment]
The problems still exist ?
What Arguments you use?, and output you get ?, paste the whole LOG file if the problem persist.

:cry:

**Comment by Omniferum** [comment]
Problem is exactly the same as before. A blank output for running without arguments, or blank and:
CRITICAL:root:Folder  does not exist !.
Folder  does not exist !.

**Comment by Omniferum** [comment]
I should perhaps point out that this is a windows specific thing as it is the only thing I use. Not a unix man.

**Comment by Omniferum** [comment]
If it helps at all the commit from I guess the day before I lodged this issue outputted as expected. So something between there and, well, now.

**Comment by juancarlospaco** [comment]
Ok. maybe next weekend I will work on this, I was busy releasing [UnicodEmoticons](https://pypi.python.org/pypi/unicodemoticon)
:smiley_cat:

**Comment by juancarlospaco** [comment]
I Pushed some new Commits that should Fix this, also has better Sorting of CSS Properties.
I will have to check it later, when I have time, but if you Test it and it works ok, let me know :exclamation: 
:smile_cat:

**Comment by Omniferum** [comment]
Traceback (most recent call last):
  File "css-html-js-minify.py", line 1451, in <module>
    main()
  File "css-html-js-minify.py", line 1447, in main
    make_post_execution_message()
  File "css-html-js-minify.py", line 1325, in make_post_execution_message
    / 1024 / 1024)
AttributeError: 'module' object has no attribute 'sysconf'

**Comment by juancarlospaco** [comment]
Ok Fixed, sorry about that :grey_exclamation:  :expressionless:

**Comment by Omniferum** [comment]
Minifies it as per usual, but still no log output like it used to. I should point out the random chance of it saying 'thank you for using' does trigger though.

**Comment by Omniferum** [comment]
CSS property sorting is still not working.

BEFORE:
padding-bottom: 10px;
padding: 5px;

AFTER:
padding-bottom: 10px;
padding: 5px;

SHOULD BE:
padding: 5px;
padding-bottom: 10px;

**Comment by juancarlospaco** [comment]
YAY :grey_exclamation: It Works :smile_cat: 

The Log file is not Ok :grey_question:  What means *no log output* :grey_question:

**Comment by Omniferum** [comment]
The cmd.exe window I run it from used to output as per: https://raw.githubusercontent.com/juancarlospaco/css-html-js-minify/master/windows-css-html-js-compressor.jpg

It still hasn't gotten back to doing that yet. I opened the issue because it stopped giving that log feedback.

**Comment by Omniferum** [comment]
Just regarding the CSS property sorting, you are already grouping them (I assume). You just need to give weighted preference to the non-hyphenated property to be at the top and all this would be fixed.

**Comment by Omniferum** [comment]
Oh, what is fixed though is that running it from the same folder no longer throws an error. So... that's fixed.

**Comment by juancarlospaco** [comment]
The Logging should be Ok now :grey_exclamation: 

Running from the same folder no longer throws an error.

**Comment by juancarlospaco** [comment]
I need to work on weighted preference to the non-hyphenated properties of the CSS, 
or maybe think if it still make sense on a Minifier... I dont know...

This is the little brother from were I back-port the CSS Sorting:
https://github.com/juancarlospaco/css-html-prettify#css-html-prettify

Feel Free to try it, just download the `css-html-prettify.py` and run: 
`python3 css-html-prettify.py --group --justify file.css` :P


This one seems Ok to Close, feel Free to Re-Open if you consider this one specificaly is not Fixed.
:octocat:

**Comment by Omniferum** [comment]
File "default.css", line 1
SyntaxError: invalid syntax

Checked my .css as nothing had changed, removed the first line as it was a comment. Instead gave:
 File "default.css", line 1
IndentationError: unexpected indent

Removed the indentation
 File "default.css", line 1
    @font-face{
         ^
SyntaxError: invalid syntax

**Comment by juancarlospaco** [comment]
Run it like:
```
[full path to python.exe between quotes]  [full path to css-html-prettify.py between quotes]  [full path to file.css between quotes]
```

**Comment by Omniferum** [comment]
Sorry, I somehow forgot to reference your script. Retarded of me.

Still no log out put.  Shall I open a new issue for that fact?

**Comment by juancarlospaco** [comment]
Fixed by https://github.com/juancarlospaco/css-html-js-minify/commit/3eddde2a66e1c786649e9827090e3be92ae49cf2  My bad :)

**Comment by Omniferum** [comment]
Fixed!
